name: Update Scholar Stats

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          #environment-file: geomod.yaml
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: true
          auto-activate-base: false

      - name: install python packages
        shell: bash -l {0}
        env:
          serpapi_token: ${{secrets.SERPAPI_TOKEN}}
        run: |
          pip install google-search-results
          python run_scholar_search.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated scholar search" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
